;===============================================================================
;-------------------------------comandos----------------------------------------
;===============================================================================
[remap]
x=x
y=y
z=z
a=a
b=b
c=c
s=s
[command]
name="s_jump"
command=~D,U
time=10
[command]
name="super1"
command=a+b
time=30
[command]
name="super2"
command=b+c
time=30
[command]
name="ultimate"
command=a+b+c
time=30
[command]
name="ultimate"
command=x
time=30
[command]
name="spc1"
command=~D,DF,F,a
time=15
[command]
name="spc2"
command=~D,DB,B,a
time=15
[command]
name="spc3"
command=~D,DF,F,b
time=15
[command]
name="spc4"
command=~D,DB,B,b
time=15
[command]
name="spc5"
command=~D,DF,F,c
time=15
[command]
name="spc6"
command=~D,DB,B,c
time=15
[command]
name="super1"
command=/s,/a
time=15
[command]
name="super2"
command=/s,/b
time=15
[command]
name="super3"
command=/s,/c
time=15
[command]
name="ff"
command=F,F
time=20
[command]
name="bb"
command=B,B
time=20
[command]
name="a"
command=a
time=1
[command]
name="b"
command=b
time=1
[command]
name="c"
command=c
time=1
[command]
name="x"
command=x
time=1
[command]
name="y"
command=y
time=1
[command]
name="z"
command=z
time=1
[command]
name="s"
command=s
time=1
[command]
name="hold_x"
command=/x
time=1
[command]
name="hold_y"
command=/y
time=1
[command]
name="hold_z"
command=/z
time=1
[command]
name="hold_a"
command=/a
time=1
[command]
name="hold_b"
command=/b
time=1
[command]
name="hold_c"
command=/c
time=1
[command]
name="hold_s"
command=/s
time=1
[command]
name="back_x"
command=/$B,x
time=1
[command]
name="back_y"
command=/$B,y
time=1
[command]
name="back_z"
command=/$B,z
time=1
[command]
name="down_x"
command=/$D,x
time=1
[command]
name="down_y"
command=/$D,y
time=1
[command]
name="down_z"
command=/$D,z
time=1
[command]
name="fwd_x"
command=/$F,x
time=1
[command]
name="fwd_y"
command=/$F,y
time=1
[command]
name="fwd_z"
command=/$F,z
time=1
[command]
name="up_x"
command=/$U,x
time=1
[command]
name="up_y"
command=/$U,y
time=1
[command]
name="up_z"
command=/$U,z
time=1
[command]
name="back_a"
command=/$B,a
time=1
[command]
name="back_b"
command=/$B,b
time=1
[command]
name="back_c"
command=/$B,c
time=1
[command]
name="down_a"
command=/$D,a
time=1
[command]
name="down_b"
command=/$D,b
time=1
[command]
name="down_c"
command=/$D,c
time=1
[command]
name="fwd_a"
command=/$F,a
time=1
[command]
name="fwd_b"
command=/$F,b
time=1
[command]
name="fwd_c"
command=/$F,c
time=1
[command]
name="up_a"
command=/$U,a
time=1
[command]
name="up_b"
command=/$U,b
time=1
[command]
name="up_c"
command=/$U,c
time=1
[command]
name="fwd"
command=$F
time=1
[command]
name="downfwd"
command=$DF
time=1
[command]
name="down"
command=$D
time=1
[command]
name="downback"
command=$DB
time=1
[command]
name="back"
command=$B
time=1
[command]
name="upback"
command=$UB
time=1
[command]
name="up"
command=$U
time=1
[command]
name="upfwd"
command=$UF
time=1
[command]
name="holdfwd"
command=/$F
time=1
[command]
name="holddownfwd"
command=/$DF
time=1
[command]
name="holddown"
command=/$D
time=1
[command]
name="holddownback"
command=/$DB
time=1
[command]
name="holdback"
command=/$B
time=1
[command]
name="holdupback"
command=/$UB
time=1
[command]
name="holdup"
command=/$U
time=1
[command]
name="holdupfwd"
command=/$UF
time=1
[command]
name="recovery"
command=x
time=1
[command]
name="recovery"
command=y
time=1
[command]
name="recovery"
command=z
time=1
[command]
name="recovery"
command=a
time=1
[command]
name="recovery"
command=b
time=1
[command]
name="recovery"
command=c
time=1
[defaults]
command.time=15
command.buffer.time=1
[statedef -1]
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=[10,109])||(stateno=[160,162])||(stateno=[200,599]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=statetype=s||statetype=a
triggerall=pos y<=0
triggerall=ailevel=0
triggerall=ifelse(var(15)=0,power>499,var(15)=1)
trigger1=command="y"
value=110
[state changestate]
type=changestate
triggerall=ctrl=1&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=statetype=s||statetype=a
triggerall=pos y<=0
triggerall=ailevel=0
trigger1=command="ff"
value=100
[state changestate]
type=changestate
triggerall=ctrl=1&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=statetype=s||statetype=a
triggerall=pos y<=0&&numexplod(101)=0
triggerall=ailevel=0
trigger1=command="bb"
value=101
[state changestate]
type=changestate
triggerall=ctrl=1&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=statetype=c||statetype=s
triggerall=ailevel=0
trigger1=command="s_jump"
trigger2=ailevel>0&&random<50
trigger2=enemy,pos y<=-100
value=80
[state changestate]
type=changestate
triggerall=ctrl=1&&ailevel=0&&roundstate=2
triggerall=stateno!=[200,3999]
triggerall=ailevel=0
trigger1=command="holdfwd"&&command="holdback"&&var(15)=1
value=cond(statetype=a,132,120)
[state changestate]
type=changestate
triggerall=(ctrl=1)&&roundstate=2&&alive=1&&enemy,stateno!=6001
triggerall=statetype=s||statetype=c
triggerall=(stateno!=[160,162])&&(stateno!=[500,501])&&stateno!=950
triggerall=ifelse(var(15)=1,power<powermax,!var(15))
triggerall=pos y=0
triggerall=ailevel=0
trigger1=command="hold_s"
trigger1=command!="holddown"
value=160
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=400))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=statetype=c||statetype=s
triggerall=ailevel=0
trigger1=command="a"
trigger1=command!="holddown"
trigger1=(command!="spc1"&&command!="spc2")
trigger1=(command!="super1"&&command!="super2"&&command!="ultimate")
value=200
[state changestate]
type=changestate
triggerall=pos y=0
triggerall=prevstateno!=210
triggerall=stateno!=210
triggerall=(ctrl=1||(stateno=[200,999]))&&roundstate=2&&alive=1&&enemy,stateno!=6001
triggerall=statetype=c||statetype=s
triggerall=ailevel=0
trigger1=command="a"
trigger1=command="holddown"
trigger1=(command!="spc1"&&command!="spc2")
trigger1=(command!="super1"&&command!="super2"&&command!="ultimate")
value=210
[state changestate]
type=changestate
triggerall=pos y<-15
triggerall=prevstateno!=215
triggerall=ctrl=1&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=statetype=s||statetype=a
triggerall=ailevel=0
trigger1=command="a"
trigger1=(command!="spc1"&&command!="spc2")
trigger1=(command!="super1"&&command!="super2"&&command!="ultimate")
value=215
[state changestate]
type=changestate
triggerall=(stateno!=[335,336])&&(prevstateno!=[335,336])
triggerall=(ctrl=1||(stateno=400))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=statetype=c||statetype=s
triggerall=ailevel=0
trigger1=command="b"
trigger1=command!="holddown"
trigger1=(command!="spc3"&&command!="spc4")
trigger1=(command!="super1"&&command!="super2"&&command!="ultimate")
value=300
[state changestate]
type=changestate
triggerall=(stateno!=[335,336])&&(prevstateno!=[335,336])
triggerall=(ctrl=1||(stateno=[200,999]))&&roundstate=2&&alive=1&&enemy,stateno!=6001
triggerall=ailevel=0
trigger1=command="b"
trigger1=command="holddown"
trigger1=(command!="spc3"&&command!="spc4")
trigger1=(command!="super1"&&command!="super2"&&command!="ultimate")
value=335
[state changestate]
type=changestate
triggerall=pos y<-5
triggerall=numexplod(325)=0
triggerall=ctrl=1&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=statetype=s||statetype=a
triggerall=ailevel=0
trigger1=command="b"
trigger1=command!="holddown"
trigger1=(command!="spc3"&&command!="spc4")
trigger1=(command!="super1"&&command!="super2"&&command!="ultimate")
value=335
[state changestate]
type=changestate
triggerall=pos y=0
triggerall=statetype=c||statetype=s
triggerall=(ctrl=1||(stateno=[10,99])||(stateno=[200,399])||(stateno=[160,161]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=stateno!=160
triggerall=ifelse(var(15)=0,power>99,var(15)=1)
triggerall=ailevel=0
trigger1=command="c"
trigger1=command!="holddown"
trigger1=(command!="spc5"&&command!="spc6")
trigger1=(command!="super1"&&command!="super2"&&command!="ultimate")
value=400
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=[50,105])||(stateno=[200,399])||(stateno=[160,161]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=pos y<0
triggerall=ailevel=0
triggerall=power>99
trigger1=command="c"
trigger1=command!="holddown"
trigger1=(command!="spc5"&&command!="spc6")
trigger1=(command!="super1"&&command!="super2"&&command!="ultimate")
value=405
[state changestate]
type=changestate
triggerall=stateno!=[420,421]
triggerall=(ctrl=1||(stateno=[50,105])||(stateno=[200,499])||(stateno=[160,161]))&&roundstate=2&&alive=1&&enemy,stateno!=6001
triggerall=power>499
triggerall=pos y=0
triggerall=ailevel=0
trigger1=command="c"
trigger1=command="holddown"
trigger1=(command!="spc5"&&command!="spc6")
trigger1=(command!="super1"&&command!="super2"&&command!="ultimate")
value=420
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=[50,105])||(stateno=[200,499])||(stateno=[160,161]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=ifelse(var(15)=0,power>999,var(15)=1)
triggerall=ailevel=0
triggerall=pos y=0
trigger1=ifelse(p2dist x<-5,command="spc3",command="spc4")
value=1000
[state changestate]
type=changestate
triggerall=(stateno=[120,155])&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=statetype=c||statetype=s
triggerall=ailevel=0&&numexplod(1100)=0
trigger1=command="recovery"
value=1100
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=[50,105])||(stateno=[200,499])||(stateno=[160,161]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=ifelse(var(15)=0,power>999,var(15)=1)
triggerall=ailevel=0
triggerall=pos y=0
trigger1=ifelse(p2dist x<-5,command="spc1",command="spc2")
value=1600
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=[50,105])||(stateno=[200,499])||(stateno=[160,161]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=ifelse(var(15)=0,power>999,var(15)=1)
triggerall=ailevel=0
triggerall=pos y=0
trigger1=ifelse(p2dist x<-5,command="spc2",command="spc1")
value=1800
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=[50,105])||(stateno=[200,499])||(stateno=[160,161]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=ifelse(var(15)=0,power>1999,var(15)=1)
triggerall=ailevel=0
triggerall=pos y<=0
trigger1=ifelse(p2dist x<-5,command="spc5",command="spc6")
value=1300
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=[50,105])||(stateno=[200,499])||(stateno=[160,161]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=ifelse(var(15)=0,power>1999,var(15)=1)
triggerall=ailevel=0
triggerall=pos y<=0
trigger1=ifelse(p2dist x<-5,command="spc6",command="spc5")
value=1400
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=[50,105])||(stateno=[200,499])||(stateno=[160,161]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=ifelse(var(15)=0,power>999,var(15)=1)
triggerall=ailevel=0
triggerall=pos y>=-7
trigger1=ifelse(p2dist x<-5,command="spc4",command="spc3")
value=1500
[state changestate]
type=changestate
triggerall=(ctrl=1||(stateno=[50,105])||(stateno=[200,499])||(stateno=[160,161]))&&alive=1&&roundstate=2&&enemy,stateno!=6001
triggerall=power=powermax
triggerall=teammode=single
triggerall=ailevel=0
triggerall=pos y=0
trigger1=command="ultimate"
value=2000